### ISSUE TITLE
strange getter behavior

### ISSUE THREAD

**Issue by dougsyer** [zenoss/zenpacklib#123]
if i add a getter to a class (ive been using @property to do it).

and if there is a problem with the getter, say an AttributeError gets raised.

then the getter silently fails.  i dont get a log event, it actually looks like the method doesnt exist at all. I havent gotten deeper than this in terms of trying to figure out why this is happening.

to illustrate I think this will reproduce it:

from . import schema
import logging
log = logging.getLogger('zen.test')

'
class MyComponent(schema.MyComponent):
    """ i do stuff
    """
    @property
    def foo(self):
        raise Exception('nutz')
    @property
    def bar(self):
        return self.im_gonna_fail'

in dmd, r being a variable pointing to an instantiated instance of MyComponent :
>>> r.bar
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: bar
>>> r.foo()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/zenoss/ZenPacks.NWN.CM/ZenPacks/NWN/CM/CMOSComponent.py", line 14, in foo
    raise Exception('nutz')
Exception: nutz
>>> r.bar()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: bar

**Comment by dougsyer** [comment]
in Ipython on my desktop I get this:

In my Ipython instance:


class MyComponent(object):
    @property
    def foo(self):
        raise Exception('nutz')
    @property
    def bar(self):
        return self.im_gonna_fail
    

v=MyComonent()
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-17-a406d564810d> in <module>()
----> 1 v=MyComonent()

NameError: name 'MyComonent' is not defined

v=MyComponent()

v.foo
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-19-5d69f2b6d47c> in <module>()
----> 1 v.foo

<ipython-input-16-3cc5b4b76d8f> in foo(self)
      2     @property
      3     def foo(self):
----> 4         raise Exception('nutz')
      5     @property
      6     def bar(self):

Exception: nutz

v.par
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-20-09c44c32b850> in <module>()
----> 1 v.par

AttributeError: 'MyComponent' object has no attribute 'par'

v.bar
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-21-cfec8cf8f5f3> in <module>()
----> 1 v.bar

<ipython-input-16-3cc5b4b76d8f> in bar(self)
      5     @property
      6     def bar(self):
----> 7         return self.im_gonna_fail
      8 

AttributeError: 'MyComponent' object has no attribute 'im_gonna_fail'

**Comment by dougsyer** [comment]
I had a getter that was failing some of the time and it was confusing trying to debug this.  at first I thought my class was just silently failing to import but it seems stranger than that.  

to try to isolate it at one point I added a mixin class with the bad method.  

if I add the bad method in a mixin class, then run the bad getter  i dont see the mixin at all.  if the method works i do see it...I may not be explaining this very well..but after running the bad method id do  __class__.__bases, and only see the schema class.  if the method works i see the schema and the mixin.

**Comment by dougsyer** [comment]
ive seen similar behavior but I cant say it was the same when you create a bad setter in the old info.py api layer.  originally that was what I thought it was but even if you dont add the @property into an attribute as an apionly you still get the same behavior.

**Comment by dougsyer** [comment]
going to add a new issue with less chaff
