### ISSUE TITLE
when adding a template to the yaml there is a traceback if the zenpack is already installed.

### ISSUE THREAD

**Issue by eedgar** [zenoss/zenpacklib#84]
AttributeError: Unable to find TEMPLATE_ID

**Comment by eedgar** [comment]
INFO:zen.ZenPackCMD:Previous ZenPack exists with same name ZenPacks.zenoss.EXAMPLEPACK
ERROR:zen.ZenPackCMD:Error removing ZenPack ZenPacks.zenoss.EXAMPLEPACK
Traceback (most recent call last):
  File "/opt/zenoss/Products/ZenUtils/ZenPackCmd.py", line 882, in RemoveZenPack
    zp.remove(dmd, leaveObjects)
  File "/home/zenoss/src/ZenPacks.zenoss.EXAMPLEPACK/ZenPacks/zenoss/EXAMPLEPACK/zenpacklib.py", line 246, in remove
    template = deviceclass.rrdTemplates._getOb(orig_mtname)
  File "/opt/zenoss/Products/ZenRelations/ToManyContRelationship.py", line 206, in _getOb
    raise AttributeError( "Unable to find %s" % id )
AttributeError: Unable to find TEMPLATE_ID
ERROR:zen.ZenPackCMD:Error installing ZenPack src/ZenPacks.zenoss.EXAMPLEPACK
Traceback (most recent call last):
  File "/opt/zenoss/Products/ZenUtils/ZenPackCmd.py", line 252, in InstallEggAndZenPack
    serviceId=serviceId)
  File "/opt/zenoss/Products/ZenUtils/ZenPackCmd.py", line 487, in InstallDistAsZenPack
    zenPack, deferFileDeletion, existing = transactional_actions()
  File "/opt/zenoss/lib/python2.7/site-packages/ZODB/transact.py", line 44, in g
    r = f(*args, **kwargs)
  File "/opt/zenoss/Products/ZenUtils/ZenPackCmd.py", line 404, in transactional_actions
    uninstallEgg=False)
  File "/opt/zenoss/Products/ZenUtils/ZenPackCmd.py", line 950, in RemoveZenPack
    raise ex
AttributeError: Unable to find TEMPLATE_ID
ERROR:zen.ZenPackCmd:zenpack command failed
Traceback (most recent call last):
  File "/opt/zenoss/Products/ZenUtils/zenpack.py", line 800, in <module>
    zp.run()
  File "/opt/zenoss/Products/ZenUtils/zenpack.py", line 227, in run
    serviceId=self.options.serviceId)
  File "/opt/zenoss/Products/ZenUtils/ZenPackCmd.py", line 268, in InstallEggAndZenPack
    raise e
AttributeError: Unable to find TEMPLATE_ID
exit status 3

**Comment by joshw** [comment]
Fix is in https://github.com/zenoss/zenpacklib/pull/86
